name: elsa
version: 1.0
author: ExslodingDogs
main: me.exslodingdogs.anticheat.AntiCheat
depend: [ProtocolLib]

commands:
  elsa:
    description: main command for elsa anticheat

permissions:
  elsa.alerts:
    default: op
