name: ELSA
version: 1.0
author: ExslodingDogs
main: me.exslodingdogs.anticheat.AntiCheat

commands:
  elsa:
    description: main command for elsa anticheat

permissions:
  elsa.alerts:
    default: op
  elsa.help:
    default: op
